# Generated by Django 3.0 on 2021-10-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='block_time',
            field=models.DateTimeField(null=True),
        ),
    ]
