# Generated by Django 3.0 on 2021-10-03 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20211003_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecondaryEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.User')),
            ],
            options={
                'db_table': 'user_secondary_email',
            },
        ),
    ]
